// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrf30HHiKrXytDp8E6E6DTXTUcIXHbMo',
    appId: '1:968826488520:web:244cb8cd29acf6c98587fd',
    messagingSenderId: '968826488520',
    projectId: 'california-faff4',
    authDomain: 'california-faff4.firebaseapp.com',
    storageBucket: 'california-faff4.appspot.com',
    measurementId: 'G-PYL8DB7CE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JSu9lOO0tQN9NC5rFBltcuNiywZNIdo',
    appId: '1:968826488520:android:d81fd5fef48b5a628587fd',
    messagingSenderId: '968826488520',
    projectId: 'california-faff4',
    storageBucket: 'california-faff4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQnJN7B3Qa_10n0v6EB8GevtZRW20YMk',
    appId: '1:968826488520:ios:806884220dfc36538587fd',
    messagingSenderId: '968826488520',
    projectId: 'california-faff4',
    storageBucket: 'california-faff4.appspot.com',
    iosClientId: '968826488520-jd3h5d8fsrdd92trm0rh3eqcoulfi6bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.califonia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBQnJN7B3Qa_10n0v6EB8GevtZRW20YMk',
    appId: '1:968826488520:ios:806884220dfc36538587fd',
    messagingSenderId: '968826488520',
    projectId: 'california-faff4',
    storageBucket: 'california-faff4.appspot.com',
    iosClientId: '968826488520-jd3h5d8fsrdd92trm0rh3eqcoulfi6bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.califonia',
  );
}
